name: CI-CD pipeline

on: 
  workflow_dispatch:
  
jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: code clone 
        run: echo "code clone form github"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: building the app
        run: echo "building the app using docker build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: image and dependencies check and test
        run: echo "code and image checking using scout"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: now deploying time
        run: echo "app deploying using docker compose"

  
