name: Hello

on: 
   #push:
     # branches: main
     workflow_dispatch:

jobs:

  greet:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest,  windows-latest , macos-latest]

    
    steps:
    
      - name: say hello to users
      
        run: echo " Hello guys  ${{ matrix.os}} "

      - name: say hello to username

        run: echo " hello  Pulkit  ${{ matrix.os}} "

  code-build:

     runs-on: ubuntu-latest

     steps:

       - name: code-clone
         run: echo "code clone is successful"
  showing-date:

    runs-on: ubuntu-latest

    steps:

      - name: showing-date
        run:  date

  version-check:

    runs-on: ubuntu-latest

    steps:
      - name: check docker version and python version
        run: docker --version && python --version
