name: Hello

on: push

jobs:

  greet:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: say hello to users
      
        run: echo "Hello guys "

      - name: say hello to username

        run: echo "hello guys $USER"

