name: Hello

on: push

jobs:

  greet:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: say hello to users
      
        run: echo "Hello guys "

      - name: say hello to username

        run: echo "hello  Pulkit "

  code-build:

     runs-on: ubuntu-latest

     steps:

       - name: code-clone
         run: echo "code clone is successful"
  showing-date:

    runs-on: ubuntu-latest

    steps:

      - name: showing-date
        run: date
